name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Resolve dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install libcurl4-openssl-dev libtidy-dev
    - name: Build
      run: make
