name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: macos-11

    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Resolve dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install \
          libcairo2-dev \
          libcsv-dev \
          libcurl4-openssl-dev \
          libjson-c-dev \
          libtidy-dev
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'ubuntu-20.04'

    - name: Resolve dependencies (macOS)
      run: |
        brew install \
          cairo \
          json-c \
          tidy-html5 \
          libcsv
      if: matrix.os == 'macos-10.15' || matrix.os == 'macos-11'

    - name: Build
      run: make
